[package]
name = "microsoft-xbox-one-emulator"
version = "1.0.0"
edition = "2021"

[dependencies]
glfw = "0.49.0"
gl = "0.14.0"
image = "0.23.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.release]
opt-level = 3